// Abstract strategy interface.
//
// The base class defines the lifecycle the pipeline drives. Concrete
// strategies (e.g. MarketMaking) implement the hot path with concrete,
// inlinable methods; virtual dispatch is used only at the integration boundary,
// never inside the per-tick inner loop.
#ifndef HFT_STRATEGY_STRATEGY_BASE_HPP_
#define HFT_STRATEGY_STRATEGY_BASE_HPP_

#include <span>

#include "common/types.hpp"
#include "order_book/order_book.hpp"

namespace hft {

class StrategyBase {
 public:
  virtual ~StrategyBase() = default;

  // Called whenever the order book for a watched token changes.
  virtual void on_book_update(Token token, const OrderBook& book) = 0;

  // Called when one of our orders is (partially) filled.
  virtual void on_fill(const FillReport& fill) = 0;

  // Called when one of our orders is cancelled or rejected by NSE.
  virtual void on_cancel(ClOrdId id, uint8_t reason_code) = 0;

  // New orders generated by the most recent on_book_update().
  virtual std::span<const Order> get_pending_orders() = 0;

  // Client order ids to cancel, generated by the most recent on_book_update().
  // Default: no cancels.
  virtual std::span<const ClOrdId> get_pending_cancels() { return {}; }
};

}  // namespace hft

#endif  // HFT_STRATEGY_STRATEGY_BASE_HPP_
